#dnf module disable nodejs -y
#dnf module enable nodejs:20 -y
#
#dnf install nodejs -y
#
#useradd roboshop
#cp cart.service /etc/systemd/system/cart.service
#
#
#mkdir /app
#
#curl -L -o /tmp/cart.zip https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
#cd /app
#unzip /tmp/cart.zip
#
#cd /app
#npm install
#
#systemctl daemon-reload
#systemctl enable cart
#systemctl restart cart

- name: cart setup
  hosts: all
  become: true
  tasks:
    - name: install nodejs:20
      ansible.builtin.dnf:
        name: '@nodejs:20'
        state: present
    - name: add user roboshop
      ansible.builtin.user:
        user: roboshop
    - name: remove app directory
      ansible.builtin.file:
        path: /app
        state: absent
    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: downlaod nd extract the file
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
        dest: /app
        remote_src: yes
    - name: install packages
      community.general.npm:
        path: /app
    - name: copy cart service file
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service
    - name: retstart nd enable the service
      ansible.builtin.systemd_service:
        state: restarted
        name: cart
        enabled: true
        daemon_reload: true