#dnf install mysql-server -y
#
#systemctl enable mysqld
#systemctl start mysqld
#
#mysql_secure_installation --set-root-pass RoboShop@1

- name: mysql setup
  hosts: all
  become: true
  tasks:
    - name: install mysql-server
      ansible.builtin.dnf:
        name: mysql-server
        state: present
    - name: mysql_secure_installation --set-root-pass RoboShop@1
      ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
    - name: restart nd enable the service
      ansible.builtin.systemd_service:
        state: restarted
        name: mysqld
        enabled: true