#dnf module disable redis -y
#dnf module enable redis:7 -y
#
#dnf install redis -y
#
#sed -i -e '/protected-mode/ c protected-mode no' -e 's/127.0.0.1/0.0.0.0/' /etc/redis/redis.conf
#
#systemctl enable redis
#systemctl start redis

- name: redis setup
  hosts: all
  become: true
  tasks:
    - name: install redis:7
      ansible.builtin.dnf:
        name: '@redis:7'
        state: present
    - name: editing the ip address of  redis conf file
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
    - name: editing the protected mode of  redis conf file
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: 'protected-mode yes'
        replace: 'protected-mode no'
    - name: restart the redis
      ansible.builtin.systemd_service:
        name: redis
        enabled: true
        state: restarted