#dnf module disable nodejs -y
#dnf module enable nodejs:20 -y
#
#dnf install nodejs -y
#
#useradd roboshop
#
#mkdir /app
#
#cp user.service /etc/systemd/system/user.service
#
#curl -L -o /tmp/user.zip https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
#cd /app
#unzip /tmp/user.zip
#
#cd /app
#npm install
#
#systemctl daemon-reload
#
#systemctl enable user
#systemctl start user


- name: user setup
  hosts: all
  become: true
  tasks:
    - name: install nodejs:20
      ansible.builtin.dnf:
        name: '@nodejs:20'
        state: present

    - name: add roboshop user
      ansible.builtin.user:
        name: roboshop

    - name: remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: add app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download nd extract the file
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
        dest: /app
        remote_src: yes

    - name: install dependencies
      community.general.npm:
        path: /app

    - name: copy user service file
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: enable nd restart the service
      ansible.builtin.systemd_service:
        state: restarted
        name: user
        enabled: true
        daemon_reload: true













